first debugged w v2 creds

diff --git a/ovpn b/ovpn
--- a/ovpn
+++ b/ovpn
@@ -16,6 +16,7 @@
 # JSON format of the credentials to be stored in OCI Vault
 #
 # {
+#   "version": 2,
 #   "default": "standard",
 #   "connections": [
 #     {
@@ -51,7 +52,7 @@ version="2.0"
 o_exec="/opt/cisco/anyconnect/bin/vpn"         # location of the vpn executable
 o_label="${OCI_VPN_LABEL:-standard}"           # label of desired connection
 o_method="${OCI_VPN_DEFAULT:-OCI}"             # default method
-o_key="${OCI_VPN_KEY}"                         # secret ocid
+o_ocid="${OCI_VPN_KEY}"                        # OCID of the secret in the vault
  
 ###############################################################################
 # Usage
@@ -73,7 +74,7 @@ function usage() {
     echo -e "  -v           verbose"
     echo -e "  -e [domain]  override the endpoint to be used"
     echo -e "  -i           write the vault instructions to stdout"
-    echo -e "  -k [key]     key to use to find the entry containing the credentials (default from environment)"
+    echo -e "  -o [ocid]    key to use to locate the entry in the vault (default from environment)"
     echo -e "  -l [label]   use the specified label to locate the correct tuple (endpoint, username, password)"
     echo -e "  -p [pwd]     override the password"
     echo -e "  -u [uname]   override the username"
@@ -112,20 +113,11 @@ function enter() {
 OCIIsWorking() {
     enter "${FUNCNAME[0]}" "${LINENO[0]}" "$@"
     vecho "Checking to see if the oci cli is installed and configured"
-    decho "Looking for OCI secret with key \"${o_key}\""
-    if json="$(oci secrets secret-bundle get --secret-id "${o_key}" 2> /dev/null)"; then
+    decho "Looking for OCI secret with key \"${o_ocid}\""
+    if json="$(oci secrets secret-bundle get --secret-id "${o_ocid}" 2> /dev/null)"; then
         json="$(echo "${json}" | jq -r '.data."secret-bundle-content".content' | base64 -d)"
-        [[ ! ${o_username} ]] && o_username="$(echo "${json}" | jq -r '.username')"
-        vecho "Got username ${o_username}"
-        [[ ! ${o_password} ]] && o_password="$(echo "${json}" | jq -r '.password')"
-        decho "Got password ${o_password}"
-        [[ ! ${o_endpoint} ]] && o_endpoint="$(echo "${json}" | \
-            jq -r '.endpoints[] | select(.l | contains("'"${o_label}"'")).u' | sed 's/https://')"
-        vecho "Got endpoint ${o_endpoint}"
     fi
-    [[ "${o_debug}" ]] && for i in o_session o_key o_username o_password o_endpoint; do echo "${i}: ${!i}"; done
-    vecho "Found username \"${o_username}\" and endpoint \"${o_endpoint}\""
-    [[ "${o_username}" && "${o_password}" && "${o_endpoint}" ]]
+    [[ "${json}" ]]
 }
 
 getCredentialsFromOCI() {
@@ -136,14 +128,36 @@ getCredentialsFromOCI() {
     # find out if a password is necessary, if so, see if one has been supplied, if not, ask for it using the prompt
     # we're done
     enter "${FUNCNAME[0]}" "${LINENO[0]}" "$@"
-    if bundle="$(oci secrets secret-bundle get --secret-id "${o_key}" 2> /dev/null)"; then
-        json="$(echo "${bundle}" | jq -r '.data."secret-bundle-content".content' | base64 -d)"
-	[[ ${o_debug} ]] && echo ${json} | jq .
-	[[ ! ${json} ]] && echo "JSON stored in secret is an invalid format or empty ${bundle}" && exit 300
-	[[ ! ${o_label} ]] && o_label="$(echo "${json}" | jq '.default')"
-	decho "Label to find is ${o_label}"
-	json="$(echo ${json} | jq '.connections[] | select(.label == "'${o_label}\"\))"
-	decho "${json}"
+    if bundle="$(oci secrets secret-bundle get --secret-id "${o_ocid}" 2> /dev/null)"; then
+        json="$(echo "${bundle}" | jq -r '.data."secret-bundle-content".content' 2>/dev/null | base64 -d)"
+	[[ ${#json} -lt 50 ]] && echo "Unexpected secret format ${bundle}." && exit 22
+	### DELETE ME
+	json="$(cat secret.json)"
+	### DELETE ME
+	vers="$(echo "${json}" | jq -r '.version')"
+	if [[ "${vers}" == "null" ]]; then
+	    echo "Invalid secret version - have you updated your format to version 2?" && exit 23
+	elif [[ ! "${vers}" -eq 2 ]]; then
+	    echo "Unexpected secret version \"${version}\"" && exit 23
+	fi
+[[ ! ${o_label} ]] && o_label="$(echo "${json}" | jq '.default')"
+	json="$(echo "${json}" | LABEL=${o_label} jq -r '.connections[] | select(.label == env.LABEL)')"
+	[[ ! "${json}" ]] && echo "Could not find label \"${o_label}\" in secret." && exit 24
+	[[ ! "${o_endpoint}" ]] && o_endpoint="$(echo "${json}" | jq -r '.endpoint')"
+	[[ ! "${o_username}" ]]  && o_username="$(echo "${json}" | jq -r '.username')"
+	if [[ ! "${o_password}" ]]; then
+	    override="$(echo "${json}" | jq -r '.password_override')"
+	    if [[ "${override^^}" == "Y" ]]; then
+		prompt="$(echo "${json}" | jq -r '.password_prompt')"
+		[[ ! "${prompt}" ]] && prompt="Enter password: "
+		read -rsp "${prompt}" o_password
+		echo ""
+	    else
+		o_password="$(echo "${json}" | jq -r '.password')"
+	    fi
+	fi
+    else
+	echo "Could not retrieve secret bundle from vault: ${bundle}" && exit 21
     fi
 }
 
@@ -163,11 +177,11 @@ joinvpn() {
                 echo "OCI CLI lookup problem; invalid oci setup or bad key provided.  Use -v for details."
                 exit 100
              fi
-	     getCredentialsFromOCI
-	     exit 0;;
-	*)   echo "Unsupoorted method of getting credentials" && exit 100;;
+	     getCredentialsFromOCI "$@";;
+	*)   echo "Unsupported method of getting credentials" && exit 100;;
     esac
     echo "Connecting to ${o_endpoint} with username ${o_username}"
+    decho "Using password ${o_password}"
     if [[ ${o_verbose} ]]; then
         printf "%s\n%s\ny\n" "${o_username}" "${o_password}" | ${o_exec} -s connect "${o_endpoint}"
     else
@@ -249,20 +263,19 @@ main() {
 ##############################################################################
 
 # set o_config o_exec o_label o_method
-unset o_debug o_endpoint o_password o_session o_username o_verbose o_instructions
+unset o_debug o_endpoint o_password o_username o_verbose o_instructions
 
-while getopts ":dhv1c:e:ik:l:op:s:u:x:" option; do
+while getopts ":dhv1e:il:o:p:u:x:" option; do
     case ${option} in
         d) o_debug=true; o_verbose=true;;
         h) usage 0;;
         v) o_verbose=true;;
+	1) "${me} ${version} no longer supports 1Password." && usage 3;;
         e) o_endpoint=${OPTARG};;
         i) o_instructions=true;;
-        k) o_key=${OPTARG};;
         l) o_label=${OPTARG};;
-        o) o_method="OCI";;
+        o) o_ocid=${OPTARG};;
         p) o_password=${OPTARG};;
-        s) o_session=${OPTARG};;
         u) o_username=${OPTARG};;
         x) o_exec=${OPTARG};;
         :) echo "Required argument to -${OPTARG} not specified."
@@ -274,9 +287,9 @@ done
 
 o_cmd="${!OPTIND:-connect}"
 
-[[ ${o_debug} ]] && for i in o_debug o_verbose o_cmd o_endpoint o_exec o_key o_method o_password o_username \
-                                     o_label o_session o_username o_url o_instructions BASH_VERSION SHELL; do
-    echo -n "${i}=\"${!i}\" "
+[[ ${o_debug} ]] && for i in o_debug o_verbose o_cmd o_endpoint o_exec o_ocid o_method o_password o_username \
+                                     o_label o_username o_url o_instructions BASH_VERSION SHELL; do
+    decho "${i}=\"${!i}\" "
 done
 decho
 
