more url grep adjustments

diff --git a/zn b/zn
--- a/zn
+++ b/zn
@@ -7,6 +7,7 @@
 # Requires icalBuddy: `$ brew install ical-buddy` (which itself requires brew)
 #
 # Change history:
+# 1.4 Bug fix for those using .../my/... and zoom URLs without a prefix
 # 1.3 Better supports other conferencing solutions and solves for urldefense URLs
 # 1.2 Now supports other URLs like WebEx, bluejeans, etc.
 # 1.1 Improved debugging strings, looked for unusual URLs containing, i.e.,
@@ -17,7 +18,7 @@
 
 base_url="${ZOOM_DOMAIN:-zoom.us}" # set to base URL for a zoom meeting
 me=$(basename "$0")
-version="1.3"
+version="1.4"
 
 ###############################################################################
 # Functions
@@ -65,13 +66,13 @@ function usage() {
 }
 
 function validConferencingURL() {
+# takes a line of text, returns true if that string contains a valid conferencing URL.  (Many URLs can be in a calendar entry).
     enter "${FUNCNAME[0]}" "${LINENO[0]}" "$@"
-    [[ $(echo "${1}" | grep -o "https://[[:alnum:]]*\.\?${base_url}/.\?/[^ \"]*") ]] && return  # zoom
-    [[ $(echo "${1}" | grep -o "https://[[:alnum:]]*\.\?webex.com/[^ \"]*") ]]        && return  # webex
-    [[ $(echo "${1}" | grep -o "https://bluejeans.com/[[:alnum:]]*/[[:alnum:]]*") ]]  && return  # bluejeans
+    [[ $(echo "${1}" | grep -o "https://[[:alnum:]]*\.\?${base_url}/.\+/[^ \"]*") ]]   && return   # zoom
+    [[ $(echo "${1}" | grep -o "https://[[:alnum:]]*\.\?webex.com/[^ \"]*") ]]         && return   # webex
+    [[ $(echo "${1}" | grep -o "https://bluejeans.com/[[:alnum:]]*/[[:alnum:]]*") ]]   && return   # bluejeans
     false
 }
-
 
 function zoomical() {
     enter "${FUNCNAME[0]}" "${LINENO[0]}" "$@"
@@ -81,52 +82,52 @@ function zoomical() {
     [[ ${o_include} ]] && includeType= || includeType="-ict CalDAV"
     decho "(icalBuddy -ea ${includeType} -b "%%%" eventsFrom:"${offsetMins}" to:"${offsetMins}")"
     while read -r line; do
-    	[[ ! ${line} ]] && continue
-    	if [[ $(echo "${line}" | grep "%%%") ]]; then
-    	    decho "New event found: ${line}"
-    	    topic[++i]=$(echo "${line}" | sed 's/^%%%\(.*$\)/\1/')
-    	    vecho "Topic: |${topic[i]}|"
-	elif [[ ! "${url[i]}" ]] && (validConferencingURL "${line}"); then
-    	    decho "Extracting URL from |${line}|"
-	    url[i]=$(echo "${line}" | sed 's|.*\(https://[[:alnum:]]*\.[[:alnum:]]*[^ ]*\)|\1|' | sed 's|[[:blank:]]||g')
-	    vecho "URL: |${url[i]}|"
-    	elif [[ ! ${block[i]} && $(echo "${line}" | grep "[0-9]\{1,2\}:[0-9]\{2\} [AP]M - [0-9]\{1,2\}") ]]; then
-    	    decho "Looking for time in ${line}"
-    	    block[i]=$(echo "${line}" | grep -o "[0-9]\{1,2\}:[0-9]\{2\} [AP]M.*$")
-    	    vecho "Block: |${block[i]}|"
-    	fi
+        [[ ! ${line} ]] && continue
+        if [[ $(echo "${line}" | grep "%%%") ]]; then
+            decho "New event found: ${line}"
+            topic[++i]=$(echo "${line}" | sed 's/^%%%\(.*$\)/\1/')
+            vecho "Topic: |${topic[i]}|"
+        elif [[ ! "${url[i]}" ]] && (validConferencingURL "${line}"); then
+            decho "Extracting URL from |${line}|"
+            url[i]=$(echo "${line}" | egrep -o 'https?://[^ ]+' | sed 's|[[:blank:]]||g')
+            vecho "URL: |${url[i]}|"
+        elif [[ ! ${block[i]} && $(echo "${line}" | grep "[0-9]\{1,2\}:[0-9]\{2\} [AP]M - [0-9]\{1,2\}") ]]; then
+            decho "Looking for time in ${line}"
+            block[i]=$(echo "${line}" | grep -o "[0-9]\{1,2\}:[0-9]\{2\} [AP]M.*$")
+            vecho "Block: |${block[i]}|"
+        fi
     done < <(icalBuddy -ea ${includeType} -b "%%%" eventsFrom:"${offsetMins}" to:"${offsetMins}")
     vecho "Number of entries found: ${#topic[@]}"
     n=${#topic[@]}
     if [[ ${n} -eq 0 ]]; then
-        # No matching events	
-	vecho "No events at ${offsetMins}"
-	echo "No zoom meetings found."
+        # No matching events    
+        vecho "No events at ${offsetMins}"
+        echo "No zoom meetings found."
     elif [[ ${n} -eq 1 ]]; then
         # Only one entry found
-	vecho "Single meeting: ${topic[0]}"
-	[[ ! ${url[0]} ]] && echo "Could not find a valid conferencing URL - skipping" && return 1
-	response=
-	[[ ${o_prompt} ]] && read -rp "Join ${topic[0]}; ${block[0]}? [y] " response
-	if [[ (! ${response}) || (${response,,} == "y") ]]; then
-	    echo "Joining ${topic[0]}..."
-	    dopen "${url[0]}"
-	else
-	    echo "Skipped"
-	fi
+        vecho "Single meeting: ${topic[0]}"
+        [[ ! ${url[0]} ]] && echo "Could not find a valid conferencing URL - skipping" && return 1
+        response=
+        [[ ${o_prompt} ]] && read -rp "Join ${topic[0]}; ${block[0]}? [y] " response
+        if [[ (! ${response}) || (${response,,} == "y") ]]; then
+            echo "Joining ${topic[0]}..."
+            dopen "${url[0]}"
+        else
+            echo "Skipped"
+        fi
     else
         # More than one entry found
-	vecho "More than one entry found, processing"
-	for (( i=0; i<n; i++ )); do
-	    echo "$(( i+1 )) Join ${topic[i]}; ${block[i]}"
-	done	
-	read -rp "Join which meeting? [cancel] " response
-	[[ (! "${response}") || ("${response,,}" == "cancel") ]] && return 1
-	[[ $(echo "${response}" | sed 's/[0-9]*//g') ]] && echo "Invalid response - skipping" && return 2
-	[[ (${response} -gt ${n}) || (${response} -lt 1) ]] && echo "Invalid meeting number - skipping" && return 3
-	[[ ! ${url[ (( --response )) ]} ]] && echo "Not a valid zoom meeting - skipping" && return 4
-	echo "Joining ${topic[response]}..."
-	dopen "${url[response]}"
+        vecho "More than one entry found, processing"
+        for (( i=0; i<n; i++ )); do
+            echo "$(( i+1 )) Join ${topic[i]}; ${block[i]}"
+        done    
+        read -rp "Join which meeting? [cancel] " response
+        [[ (! "${response}") || ("${response,,}" == "cancel") ]] && return 1
+        [[ $(echo "${response}" | sed 's/[0-9]*//g') ]] && echo "Invalid response - skipping" && return 2
+        [[ (${response} -gt ${n}) || (${response} -lt 1) ]] && echo "Invalid meeting number - skipping" && return 3
+        [[ ! ${url[ (( --response )) ]} ]] && echo "Not a valid zoom meeting - skipping" && return 4
+        echo "Joining ${topic[response]}..."
+        dopen "${url[response]}"
     fi
 }
 
@@ -141,25 +142,25 @@ function zoomwith() {
 function mainprog() {
     enter "${FUNCNAME[0]}" "${LINENO[0]}" "$@"
     if [[ ! $(which icalBuddy) ]]; then
-    	echo "This script requires icalBuddy to be installed"
-    	if [[ $(which brew) ]]; then
-    	    read -rp 'Install icalBuddy through brew [y] ' response
-    	    [[ ! ${response} || ("${response}" == "y") ]] && brew install ical-buddy
-    	else
-    	    echo "Easiest install is through homebrew at https://brew.sh/"
-    	fi
-    	exit 2
+        echo "This script requires icalBuddy to be installed"
+        if [[ $(which brew) ]]; then
+            read -rp 'Install icalBuddy through brew [y] ' response
+            [[ ! ${response} || ("${response}" == "y") ]] && brew install ical-buddy
+        else
+            echo "Easiest install is through homebrew at https://brew.sh/"
+        fi
+        exit 2
     fi
 
     [[ ${o_debug} ]] && for i in base_url o_debug o_include o_minutes o_prompt o_verbose o_with BASH_VERSION SHELL; do
-    	echo -n "${i}=\"${!i}\" "
+        echo -n "${i}=\"${!i}\" "
     done
     decho
     
     if [[ ${o_with} ]]; then
-	zoomwith "$@"
+        zoomwith "$@"
     else
-	zoomical "$@"
+        zoomical "$@"
     fi
 }
 
@@ -170,21 +171,21 @@ function mainprog() {
 unset o_debug o_include o_minutes o_prompt o_verbose o_with
 while getopts ":dhipm:nu:vw:" option; do
     case ${option} in
-	d) o_debug=true; o_verbose=true;;
-	h) usage;;
-	i) o_include=true;;
-	m) o_minutes=${OPTARG}
-	   [[ ! $(echo "${o_minutes}" | grep "^[-+]\?[0-9]\{1,4\}$") ]] && usage "$@"
-	   [[ ! $(echo "${o_minutes}" | grep "^[-+].*") ]] && o_minutes="+${o_minutes}";;
-	n) o_with="me";;
-	p) o_prompt=true;;
-	u) base_url=${OPTARG,,};;
-	v) o_verbose=true;;
-	w) o_with=${OPTARG^};;
-	:) echo "Required argument to -${OPTARG} not specified."
-	   exit 1;;
-	*) echo "Option -${option} not recognized."
-	   usage "$@";;
+        d) o_debug=true; o_verbose=true;;
+        h) usage;;
+        i) o_include=true;;
+        m) o_minutes=${OPTARG}
+           [[ ! $(echo "${o_minutes}" | grep "^[-+]\?[0-9]\{1,4\}$") ]] && usage "$@"
+           [[ ! $(echo "${o_minutes}" | grep "^[-+].*") ]] && o_minutes="+${o_minutes}";;
+        n) o_with="me";;
+        p) o_prompt=true;;
+        u) base_url=${OPTARG,,};;
+        v) o_verbose=true;;
+        w) o_with=${OPTARG^};;
+        :) echo "Required argument to -${OPTARG} not specified."
+           exit 1;;
+        *) echo "Option -${option} not recognized."
+           usage "$@";;
     esac
 done
 
